language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarqube: true

script:
  - ./gradlew clean build
  - ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
