name: Build and publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build LEGUI
    runs-on: ubuntu-latest
    steps:

      # CHECKOUT
      - uses: actions/checkout@v2

      # EVALUATE VARIABLES
      - name: Get JSON Property
        id: extract_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: version.json
          prop_path: version

      - name: Set environment variables
        run: |
          echo "branch=develop" >> $GITHUB_ENV
          echo "publishUrl=git:releases://git@github.com:SpinyOwl/repo.git" >> $GITHUB_ENV
          echo "version=${{steps.extract_version.outputs.prop}}" >> $GITHUB_ENV
          echo "repoUrl=https://github.com/SpinyOwl/repo/tree/releases/org/liquidengine/legui" >> $GITHUB_ENV

      # CALL WEBHOOK
      - name: Send message build started
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          color: '#808080'
          description: Build started
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      # PREPARE AND BUILD
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: ./gradlew build

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test

      # SONAR CHECK
      - name: Run sonarqube check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          sonarLogin: ${{secrets.sonarToken}}
          sonarUsername: ${{secrets.sonarUsername}}
          sonarPassword: ${{secrets.sonarPassword}}
          JAVA_OPTS: -Xmx3072m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m
          GRADLE_OPTS: -Xmx3800m -XX:ReservedCodeCacheSize=128m -Dorg.gradle.daemon=false
        run: ./gradlew sonarqube

      # PUBLISH ARTIFACTS
      - name: Prepare environment to publish artifacts
        if: "!contains(github.event.head_commit.message, '[skip publish]')"
        run: |
          git config --global user.name ${{ secrets.publishUsername }}
          git config --global user.email ${{ secrets.publishEmail }}

      - name: Configure SSH to publish artifacts
        if: "!contains(github.event.head_commit.message, '[skip publish]')"
        uses: MrSquaare/ssh-setup-action@v1.0.1
        with:
          host: github.com
          private-key: ${{ secrets.REPO_TOKEN }}

      - name: Publish artifacts to github repository
        if: "!contains(github.event.head_commit.message, '[skip publish]')"
        env:
          publishUsername: ${{ secrets.publishUsername }}
          publishPassword: ${{ secrets.publishPassword }}
        run: ./gradlew uploadArchives

      # CALL WEBHOOK
      - name: Send message build finished
        uses: rjstone/discord-webhook-notify@v1
        if: success() && !contains(github.event.head_commit.message, '[skip publish]')
        with:
          severity: info
          details: |
            Build successfully finished.
            **Artifact version** - `${{env.version}}`.
            Browse artifacts: [Browse artifacts](${{env.repoUrl}}${{env.version}})
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      - name: Send message build finished
        uses: rjstone/discord-webhook-notify@v1
        if: success() && contains(github.event.head_commit.message, '[skip publish]')
        with:
          severity: info
          details: |
            Build successfully finished.
            Browse artifacts: [Browse artifacts](${{env.repoUrl}})
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      - name: Send message build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Build failed.
            Browse artifacts: [Browse artifacts](${{env.repoUrl}})
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      - name: Send message build cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: |
            Build cancelled.
            Browse artifacts: [Browse artifacts](${{env.repoUrl}})
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}
