name: Build and check PR

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build PR for LEGUI
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v2

      # PREPARE AND BUILD
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: ./gradlew build

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test
