name: Build and publish

on:
  pull_request:
    branches:
      - releases
      - develop

jobs:
  build:
    name: Build PR for LEGUI
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v2

      # EVALUATE VARIABLES
      - name: Set env to develop
        if: github.base_ref == 'refs/heads/develop'
        run: |
          echo "::set-env name=branch::develop";

      - name: Set env to release
        if: github.base_ref == 'refs/heads/releases'
        run: |
          echo "::set-env name=branch::releases"

      # CALL WEBHOOK

      - name: send message build started
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          color: '#808080'
          description: Build started on branch `${{env.branch}}`
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      # PREPARE AND BUILD
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: ./gradlew build

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test

      # SONAR CHECK
      - name: Run sonarqube check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          sonarLogin: ${{secrets.sonarToken}}
          sonarUsername: ${{secrets.sonarUsername}}
          sonarPassword: ${{secrets.sonarPassword}}
          JAVA_OPTS: -Xmx3072m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m
          GRADLE_OPTS: -Xmx3800m -XX:ReservedCodeCacheSize=128m -Dorg.gradle.daemon=false
        run: ./gradlew sonarqube

      # CALL WEBHOOK
      - name: send message build finished
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          description: |
            Build successfully finished for PR to `${{env.branch}}`
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      - name: send failure message
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          description: |
            Build failed for PR to `${{env.branch}}`
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}

      - name: send cancelled message
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          description: |
            Build cancelled for PR to `${{env.branch}}`
          footer: "https://github.com/SpinyOwl/legui"
          webhookUrl:  ${{ secrets.WEBHOOK_URL }}